//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deville.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineAppointment
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string AuthorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
