//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deville.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoAlbum
    {
        public PhotoAlbum()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImgCover { get; set; }
        public int GalleryId { get; set; }
        public int Status { get; set; }
    
        public virtual PhotoGallery PhotoGallery { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
