//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deville.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImgCover { get; set; }
        public string Article { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CategoryId { get; set; }
        public bool IsNovelty { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
