//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deville.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategory
    {
        public ServiceCategory()
        {
            this.Services = new HashSet<Service>();
            this.ServiceSubcategories = new HashSet<ServiceSubcategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImgCover { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<ServiceSubcategory> ServiceSubcategories { get; set; }
    }
}
