//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deville.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSubcategory
    {
        public ServiceSubcategory()
        {
            this.Services = new HashSet<Service>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public int Status { get; set; }
    
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}
