//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deville.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.OnlineAppointments = new HashSet<OnlineAppointment>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> VirtuosoPrice { get; set; }
        public Nullable<decimal> ExpertPrice { get; set; }
        public Nullable<decimal> HandymanPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImgCover { get; set; }
        public Nullable<int> SubcategoryId { get; set; }
    
        public virtual ICollection<OnlineAppointment> OnlineAppointments { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ServiceSubcategory ServiceSubcategory { get; set; }
    }
}
