//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDocument
    {
        public string DocumentPath { get; set; }
        public string DocumentTitle { get; set; }
        public System.DateTime UploadDate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int Id { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
