//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Articles = new HashSet<Article>();
            this.InfoCards = new HashSet<InfoCard>();
            this.News = new HashSet<News>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<InfoCard> InfoCards { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual Role Role { get; set; }
    }
}
